services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_ct
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    networks:
      - default

volumes:
  portainer_data:
    name: portainer_data
    driver: local
    external: false

networks:
  default:
    name: portainer_network
    driver: bridge
    external: false

      